title: æ©™æ±ä¸ç”œ # name of the site
author: totoro625 # name of site's author
email: i@run.cm # email of site's author
url: https://www.totoro.pub # root address of the site
baseurl: "/" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: TOTORO625ã®Special totoro625 æ˜¯æ¡å’¸é±¼
permalink: /:slug

favicon: "favicon.ico" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

# remote_theme: riggraz/no-style-please
theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: "ã€è¿”å›ã€ğŸ§€ãƒ¾(â‰§â–½â‰¦*)o" # customize text for homepage link in post layout
  date_format: "ã€æ—¶é—´ã€ğŸ“¢%Yå¹´%mæœˆ%dæ—¥" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
